### ISSUE TITLE
Unable to retrieve any statistics

### ISSUE THREAD

**Issue by alvarolorentedev** [tobilg/npm-stats-cli#2]
I am getting this error when I run the CLI
```
 node node_modules/npm-stats-cli/bin/index.js --user tobilg --start 2017-12-01 --end 2017-12-05 --granularity daily --output tsv
(node:42087) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/alvaro/Workspace/asasa/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/alvaro/Workspace/asasa/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/alvaro/Workspace/asasa/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:42087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insideof an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:42087) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

what i think is happening is the default api url for npm is giving 404

**Comment by tobilg** [comment]
This is fixed in the most recent version `0.2.0`
